### ISSUE TITLE
Did you forget to commit the file?

### ISSUE THREAD

**Issue by VGLogg** [fnc12/embeddedRest#1]
With your last commit, you changed this:

 -#include "rapidjson/document.h"
-#include "rapidjson/stringbuffer.h"
-#include "rapidjson/writer.h"
+#include "JsonValueAdapter.hpp"

in Classes/UrlRequest.hpp.

But there isn't a new file called JsonValueAdapter.hpp. Did you forget to commit it or did i miss something?

**Comment by fnc12** [comment]
@VGLogg forgot about it. Added a minute age. Check it out
